### ISSUE TITLE
Adversarial testing datasets: PhiX

### ISSUE THREAD

**Issue by TransGirlCodes** [BioJulia/GenomeGraphs.jl#11]
We should add some adversarial testing datasets either to BioSequenceGraphs.

They may take up some space and so we'll have to think about how to do this with bigger datasets.

But for now, I propose adding a PhiX dataset: We can use the PhiX reference genome sequence. Use [Pseudoseq.jl](https://github.com/bioinfologics/Pseudoseq.jl) to  generate paired-end reads. We will need to decide on a read length and average insert size. Once we have the read files we can include the reference and the reads, and use that data to test how our graph functions are working.

**Comment by ardakdemir** [comment]
I have used ecoli-ref.fasta available under the example folder of Pseudoseq.jl to generate very short reads (read_length = 20). Then successfully constructed the dbg for k= 10. The resulting graph contains 742343. I will be using this graph for testing the implemented functionalities. It is available in my local  yet I can not push it as the file has size 575MB.
