### ISSUE TITLE
Error when including BioSequenceGraphs.jl

### ISSUE THREAD

**Issue by ardakdemir** [BioJulia/GenomeGraphs.jl#3]
<@re_str not defined Error -->

I have cloned the repository to my local.
When including the package with "include("BioSequenceGraphs.jl")" I get the following error:

LoadError: LoadError: UndefVarError: @re_str not defined

For now, I have just removed the line 

```
include("GFA1/GFA1.jl")
```

from BioSequenceGraphs.jl to be able to run the package smoothly.

**Comment by TransGirlCodes** [comment]
@ardakdemir Do you still have this issue or did we fix it?

**Comment by ardakdemir** [comment]
I still could not find a clean way out of this

2019年7月3日(水) 22:55 Ben J. Ward <notifications@github.com>:
