### ISSUE TITLE
Maybe a typo in SequenceGraph.jl

### ISSUE THREAD

**Issue by ardakdemir** [BioJulia/GenomeGraphs.jl#4]
I am not sure if this is also a design concept or not  but I think there is a typo in add_node function in SequenceGraph.jl:

```
function add_node!(sg::SequenceGraph, n::SequenceGraphNode)
    newlen = length(push!(nodes(sg)))
    resize!(links(sg), newlen)
    return newlen
end
```
I think the push function should also include n as follows:
```
    newlen = length(push!(nodes(sg),n))
```
I am pushing an updated issue to the gsoc branch

**Comment by TransGirlCodes** [comment]
This has been fixed. I'll close this issue as it's quite old.
